// src/app/pages/Login/Login.tsx
import { ReactComponent as Logo } from "../../../assets/svgs/logo.svg";
import React from "react";

export default function Login() {
    return (
        <>
            <div className="img-background d-flex align-items-center justify-content-center">
                <div className="box">
                    <div className="d-flex justify-content-center p-3">
                        <p className="m-auto text-mini-logo">
                            <Logo height={"45px"} width={"45px"} />&nbsp;&nbsp;Easy Chef
                        </p>
                    </div>

                    <div className="form-group">
                        <label htmlFor="input-email" className="form-label">Email address</label>
                        <input type="email" className="form-control" id="input-email" name="email" aria-describedby="emailHelp" placeholder="Email"/>
                        <small id="emailHelp" className="help-block">Não tem uma conta? Crie uma</small>
                    </div>
                    <div className="form-group">
                        <label htmlFor="input-account-name" className="form-label">Password</label>
                        <input type="password" className="form-control" id="input-password" name="password" placeholder="Password"/>
                        <small className="help-block">Esqueceu seu e-mail ou senha?</small>
                    </div>

                    <div className="d-flex justify-content-center p-3">
                        <button className="light-button">Entrar</button>
                    </div>
                </div>
            </div>
        </>
    );
}

// src/app/modules/autenticacao/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  public hide: boolean = true;
  constructor() { }

  ngOnInit(): void {
  }
}

<div class="auth-background p-5 h-100 d-flex">
  <div class="dark-card">
    <div class="w-100 d-flex pb-5">
      <span class="logo mx-auto">
        <img src="../../../../assets/images/icons/easy-chef-logo.svg" alt="icon" width="45px" height="45px">&nbsp;EasyChef
      </span>
    </div>

    <form>
      <mat-form-field appearance="outline" class="w-100 pb-3">
        <mat-label>E-mail</mat-label>
        <input matInput type="text">
        <mat-hint>Não tem uma conta? <a class="light-link" href="#">Crie uma</a></mat-hint>
      </mat-form-field>
      <mat-form-field appearance="outline" class="w-100 pb-3">
        <mat-label>Senha</mat-label>
        <input matInput [type]="hide ? 'password' : 'text'">
        <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Esconder senha'" [attr.aria-pressed]="hide" style="background-color: transparent; border: none; color: inherit;">
          <mat-icon>{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
        </button>
        <mat-hint>Esqueceu seu <a class="light-link" href="#">e-mail ou senha</a>?</mat-hint>
      </mat-form-field>

      <div class="w-100 text-center">
        <button mat-stroked-button class="light-button">Entrar</button>
      </div>
    </form>
  </div>
</div>
